# Generated by Django 4.2.3 on 2023-07-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stafflevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stafflevel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stafftype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stafftype_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stafflevel')),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stafftype')),
            ],
        ),
    ]
