# Generated by Django 4.2.3 on 2023-07-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
